spring.application.name=lab-inventario-springboot

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/inventario_hospital
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080